language: go

go:
  - 1.11.x
  - 1.12.x
  - tip

env:
- GO111MODULE=on

before_script:
  - go get github.com/mitchellh/gox

script: 
  - make check_fmt
  - go test -v ./...
  - make build

#deploy:
#  skip_cleanup: true
#  provider: script
#  script: make release
#  on:
#    branch: master
